In [10]:
import pyspark
import pydataset

In [11]:
spark = pyspark.sql.SparkSession.builder.getOrCreate()

In [12]:
spark

In [13]:
import pandas as pd
import numpy as np

np.random.seed(456)

pandas_dataframe = pd.DataFrame(
    dict(n=np.arange(20), group=np.random.choice(list("abc"), 20))
)
pandas_dataframe

     n group
0    0     b
1    1     b
2    2     c
3    3     a
4    4     c
5    5     c
6    6     a
7    7     b
8    8     a
9    9     b
10  10     b
11  11     a
12  12     b
13  13     a
14  14     b
15  15     b
16  16     c
17  17     c
18  18     a
19  19     c

In [14]:
df = spark.createDataFrame(pandas_dataframe)
df

DataFrame[n: bigint, group: string]

In [15]:
df.show(5)

+---+-----+
|  n|group|
+---+-----+
|  0|    b|
|  1|    b|
|  2|    c|
|  3|    a|
|  4|    c|
+---+-----+
only showing top 5 rows

In [18]:
df.describe()

DataFrame[summary: string, n: string, group: string]

In [9]:
df.describe().show()

+-------+-----------------+-----+
|summary|                n|group|
+-------+-----------------+-----+
|  count|               20|   20|
|   mean|              9.5| null|
| stddev|5.916079783099616| null|
|    min|                0|    a|
|    max|               19|    c|
+-------+-----------------+-----+

In [19]:
from pydataset import data

mpg = spark.createDataFrame(data("mpg"))
mpg.show(5)

+------------+-----+-----+----+---+----------+---+---+---+---+-------+
|manufacturer|model|displ|year|cyl|     trans|drv|cty|hwy| fl|  class|
+------------+-----+-----+----+---+----------+---+---+---+---+-------+
|        audi|   a4|  1.8|1999|  4|  auto(l5)|  f| 18| 29|  p|compact|
|        audi|   a4|  1.8|1999|  4|manual(m5)|  f| 21| 29|  p|compact|
|        audi|   a4|  2.0|2008|  4|manual(m6)|  f| 20| 31|  p|compact|
|        audi|   a4|  2.0|2008|  4|  auto(av)|  f| 21| 30|  p|compact|
|        audi|   a4|  2.8|1999|  6|  auto(l5)|  f| 16| 26|  p|compact|
+------------+-----+-----+----+---+----------+---+---+---+---+-------+
only showing top 5 rows

In [27]:
data()

,dataset_id,title
0,AirPassengers,Monthly Airline Passenger Numbers 1949-1960
1,BJsales,Sales Data with Leading Indicator
2,BOD,Biochemical Oxygen Demand
3,Formaldehyde,Determination of Formaldehyde
4,HairEyeColor,Hair and Eye Color of Statistics Students
5,InsectSprays,Effectiveness of Insect Sprays
6,JohnsonJohnson,Quarterly Earnings per Johnson & Johnson Share
7,LakeHuron,Level of Lake Huron 1875-1972
8,LifeCycleSavings,Intercountry Life-Cycle Savings Data
9,Nile,Flow of the River Nile
10,OrchardSprays,Potency of Orchard Sprays
11,PlantGrowth,Results from an Experiment on Plant Growth
12,Puromycin,Reaction Velocity of an Enzymatic Reaction
13,Titanic,Survival of passengers on the Titanic
14,ToothGrowth,The Effect of Vitamin C on Tooth Growth in Guinea Pigs
15,UCBAdmissions,Student Admissions at UC Berkeley
16,UKDriverDeaths,Road Casualties in Great Britain 1969-84
17,UKgas,UK Quarterly Gas Consumption
18,USAccDeaths,Accidental Deaths in the US 1973-1978
19,USArrests,Violent Crime Rates by US State
20,USJudgeRatings,Lawyers' Ratings of State Judges in the US Superior Court
21,USPersonalExpenditure,Personal Expenditure Data
22,VADeaths,Death Rates in Virginia (1940)
23,WWWusage,Internet Usage per Minute
24,WorldPhones,The World's Telephones
25,airmiles,"Passenger Miles on Commercial US Airlines, 1937-1960"
26,airquality,New York Air Quality Measurements
27,anscombe,Anscombe's Quartet of 'Identical' Simple Linear Regressions
28,attenu,The Joyner-Boore Attenuation Data
29,attitude,The Chatterjee-Price Attitude Data
30,austres,Quarterly Time Series of the Number of Australian Residents
31,cars,Speed and Stopping Distances of Cars
32,chickwts,Chicken Weights by Feed Type
33,co2,Mauna Loa Atmospheric CO2 Concentration
34,crimtab,Student's 3000 Criminals Data
35,discoveries,Yearly Numbers of Important Discoveries
36,esoph,"Smoking, Alcohol and (O)esophageal Cancer"
37,euro,Conversion Rates of Euro Currencies
38,faithful,Old Faithful Geyser Data
39,freeny,Freeny's Revenue Data
40,infert,Infertility after Spontaneous and Induced Abortion
41,iris,Edgar Anderson's Iris Data
42,islands,Areas of the World's Major Landmasses
43,lh,Luteinizing Hormone in Blood Samples
44,longley,Longley's Economic Regression Data
45,lynx,Annual Canadian Lynx trappings 1821-1934
46,morley,Michelson Speed of Light Data
47,mtcars,Motor Trend Car Road Tests
48,nhtemp,Average Yearly Temperatures in New Haven
49,nottem,"Average Monthly Temperatures at Nottingham, 1920-1939"
50,npk,"Classical N, P, K Factorial Experiment"
51,occupationalStatus,Occupational Status of Fathers and their Sons
52,precip,Annual Precipitation in US Cities
53,presidents,Quarterly Approval Ratings of US Presidents
54,pressure,Vapor Pressure of Mercury as a Function of Temperature
55,quakes,Locations of Earthquakes off Fiji
56,randu,Random Numbers from Congruential Generator RANDU
57,rivers,Lengths of Major North American Rivers
58,rock,Measurements on Petroleum Rock Samples
59,sleep,Student's Sleep Data
60,stackloss,Brownlee's Stack Loss Plant Data
61,sunspot.month,"Monthly Sunspot Data, from 1749 to ""Present"""
62,sunspot.year,"Yearly Sunspot Data, 1700-1988"
63,sunspots,"Monthly Sunspot Numbers, 1749-1983"
64,swiss,Swiss Fertility and Socioeconomic Indicators (1888) Data
65,treering,"Yearly Treering Data, -6000-1979"
66,trees,"Girth, Height and Volume for Black Cherry Trees"
67,uspop,Populations Recorded by the US Census
68,volcano,Topographic Information on Auckland's Maunga Whau Volcano
69,warpbreaks,The Number of Breaks in Yarn during Weaving
70,women,Average Heights and Weights for American Women
71,acme,Monthly Excess Returns
72,aids,Delay in AIDS Reporting in England and Wales
73,aircondit,Failures of Air-conditioning Equipment
74,aircondit7,Failures of Air-conditioning Equipment
75,amis,Car Speeding and Warning Signs
76,aml,Remission Times for Acute Myelogenous Leukaemia
77,bigcity,Population of U.S. Cities
78,brambles,Spatial Location of Bramble Canes
79,breslow,Smoking Deaths Among Doctors
80,calcium,Calcium Uptake Data
81,cane,Sugar-cane Disease Data
82,capability,Simulated Manufacturing Process Data
83,catsM,Weight Data for Domestic Cats
84,cav,Position of Muscle Caveolae
...,...,...
672,students,Student Risk Taking
673,suicides,Crowd Baiting Behaviour and Suicides
674,toothpaste,Toothpaste Data
675,voting,House of Representatives Voting Data
676,water,Mortality and Water Hardness
677,watervoles,Water Voles Data
678,waves,Electricity from Wave Power at Sea
679,weightgain,Gain in Weight of Rats
680,womensrole,Womens Role in Society
681,Bechtoldt,Seven data sets showing a bifactor solution.
682,Bechtoldt.1,Seven data sets showing a bifactor solution.
683,Bechtoldt.2,Seven data sets showing a bifactor solution.
684,Dwyer,8 cognitive variables used by Dwyer for an example.
685,Gleser,"Example data from Gleser, Cronbach and Rajaratnam (1965) to show basic principles of g..."
686,Gorsuch,Example data set from Gorsuch (1997) for an example factor extension.
687,Harman.5,5 socio-economic variables from Harman (1967)
688,Harman.8,"Correlations of eight physical variables (from Harman, 1966)"
689,Harman.political,Eight political variables used by Harman (1967) as example 8.17
690,Holzinger,Seven data sets showing a bifactor solution.
691,Holzinger.9,Seven data sets showing a bifactor solution.
692,Reise,Seven data sets showing a bifactor solution.
693,Schmid,12 variables created by Schmid and Leiman to show the Schmid-Leiman Transformation
694,Thurstone,Seven data sets showing a bifactor solution.
695,Thurstone.33,Seven data sets showing a bifactor solution.
696,Tucker,9 Cognitive variables discussed by Tucker and Lewis (1973)
697,ability,16 ability items scored as correct or incorrect.
698,affect,Two data sets of affect and arousal scores as a function of personality and movie cond...
699,bfi,25 Personality items representing 5 factors
700,bfi.dictionary,25 Personality items representing 5 factors
701,blot,Bond's Logical Operations Test - BLOT
702,burt,11 emotional variables from Burt (1915)
703,cities,Distances between 11 US cities
704,cubits,Galton's example of the relationship between height and 'cubit' or forearm length
705,cushny,A data set from Cushny and Peebles (1905) on the effect of three drugs on hours of sle...
706,epi,Eysenck Personality Inventory (EPI) data for 3570 participants
707,epi.bfi,13 personality scales from the Eysenck Personality Inventory and Big 5 inventory
708,epi.dictionary,Eysenck Personality Inventory (EPI) data for 3570 participants
709,galton,Galton's Mid parent child height data
710,heights,A data.frame of the Galton (1888) height and cubit data set.
711,income,US family income from US census 2008
712,iqitems,16 multiple choice IQ items
713,msq,75 mood items from the Motivational State Questionnaire for 3896 participants
714,neo,NEO correlation matrix from the NEO_PI_R manual
715,peas,Galton's Peas
716,sat.act,"3 Measures of ability: SATV, SATQ, ACT"
717,withinBetween,An example of the distinction between within group and between group correlations
718,Bosco,Boscovich Data
719,CobarOre,Cobar Ore data
720,Mammals,Garland(1983) Data on Running Speed of Mammals
721,barro,Barro Data
722,engel,Engel Data
723,uis,UIS Drug Treatment study data
724,dietox,Growth curves of pigs in a 3x3 factorial experiment
725,koch,Ordinal Data from Koch
726,ohio,Ohio Children Wheeze Status
727,respdis,Clustered Ordinal Respiratory Disorder
728,respiratory,Data from a clinical trial comparing two treatments for a respiratory illness
729,seizure,Epiliptic Seizures
730,sitka89,Growth of Sitka Spruce Trees
731,spruce,Log-size of 79 Sitka spruce trees
732,liver,Liver related laboratory data
733,portpirie,"Rain, wavesurge and portpirie datasets."
734,rain,"Rain, wavesurge and portpirie datasets."
735,summer,"Air pollution data, separately for summer and winter months"
736,wavesurge,"Rain, wavesurge and portpirie datasets."
737,winter,"Air pollution data, separately for summer and winter months"
738,arthritis,Rheumatoid Arthritis Clinical Trial
739,housing,Homeless Data
740,bmw,Daily Log Returns on BMW Share Price
741,danish,Danish Fire Insurance Claims
742,nidd.annual,The River Nidd Data
743,nidd.thresh,The River Nidd Data
744,siemens,Daily Log Returns on Siemens Share Price
745,sp.raw,SP Data to June 1993
746,spto87,SP Return Data to October 1987
747,Dyestuff,Yield of dyestuff by batch
748,Dyestuff2,Yield of dyestuff by batch
749,InstEval,University Lecture/Instructor Evaluations by Students at ETH
750,Pastes,Paste strength by batch and cask
751,Penicillin,Variation in penicillin testing
752,VerbAgg,Verbal Aggression item responses
753,cake,Breakage Angle of Chocolate Cakes
754,cbpp,Contagious bovine pleuropneumonia
755,grouseticks,Data on red grouse ticks from Elston et al. 2001
756,sleepstudy,Reaction times in a sleep deprivation study

In [25]:
help(pydataset)

Help on package pydataset:

NAME
    pydataset

DESCRIPTION
    # __init__.py
    # main interface to pydataset module

PACKAGE CONTENTS
    datasets_handler
    dump_data
    locate_datasets
    support
    utils (package)

FUNCTIONS
    data(item=None, show_doc=False)
        loads a datasaet (from in-modules datasets) in a dataframe data structure.

        Args:
            item (str)      : name of the dataset to load.
            show_doc (bool) : to show the dataset's documentation.

        Examples:

        >>> iris = data('iris')


        >>> data('titanic', show_doc=True)
            : returns the dataset's documentation.

        >>> data()
            : like help(), returns a dataframe [Item, Title]
            for a list of the available datasets.

FILE
    /usr/local/anaconda3/lib/python3.7/site-packages/pydataset/__init__.py

In [20]:
mpg.hwy

Column<b'hwy'>

In [21]:
mpg.select(mpg.hwy, mpg.cty, mpg.model)

DataFrame[hwy: bigint, cty: bigint, model: string]

In [22]:
mpg.select(mpg.hwy, mpg.cty, mpg.model).show(10)

+---+---+----------+
|hwy|cty|     model|
+---+---+----------+
| 29| 18|        a4|
| 29| 21|        a4|
| 31| 20|        a4|
| 30| 21|        a4|
| 26| 16|        a4|
| 26| 18|        a4|
| 27| 18|        a4|
| 26| 18|a4 quattro|
| 25| 16|a4 quattro|
| 28| 20|a4 quattro|
+---+---+----------+
only showing top 10 rows

In [23]:
pydataset.data('mpg')

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
6,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
7,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
8,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
9,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
10,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact
11,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact
12,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact
13,audi,a4 quattro,2.8,1999,6,manual(m5),4,17,25,p,compact
14,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact
15,audi,a4 quattro,3.1,2008,6,manual(m6),4,15,25,p,compact
16,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize
17,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize
18,audi,a6 quattro,4.2,2008,8,auto(s6),4,16,23,p,midsize
19,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv
21,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
22,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv
23,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv
24,chevrolet,corvette,5.7,1999,8,manual(m6),r,16,26,p,2seater
25,chevrolet,corvette,5.7,1999,8,auto(l4),r,15,23,p,2seater
26,chevrolet,corvette,6.2,2008,8,manual(m6),r,16,26,p,2seater
27,chevrolet,corvette,6.2,2008,8,auto(s6),r,15,25,p,2seater
28,chevrolet,corvette,7.0,2008,8,manual(m6),r,15,24,p,2seater
29,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,14,19,r,suv
30,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,11,14,e,suv
31,chevrolet,k1500 tahoe 4wd,5.7,1999,8,auto(l4),4,11,15,r,suv
32,chevrolet,k1500 tahoe 4wd,6.5,1999,8,auto(l4),4,14,17,d,suv
33,chevrolet,malibu,2.4,1999,4,auto(l4),f,19,27,r,midsize
34,chevrolet,malibu,2.4,2008,4,auto(l4),f,22,30,r,midsize
35,chevrolet,malibu,3.1,1999,6,auto(l4),f,18,26,r,midsize
36,chevrolet,malibu,3.5,2008,6,auto(l4),f,18,29,r,midsize
37,chevrolet,malibu,3.6,2008,6,auto(s6),f,17,26,r,midsize
38,dodge,caravan 2wd,2.4,1999,4,auto(l3),f,18,24,r,minivan
39,dodge,caravan 2wd,3.0,1999,6,auto(l4),f,17,24,r,minivan
40,dodge,caravan 2wd,3.3,1999,6,auto(l4),f,16,22,r,minivan
41,dodge,caravan 2wd,3.3,1999,6,auto(l4),f,16,22,r,minivan
42,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,17,24,r,minivan
43,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,17,24,r,minivan
44,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,11,17,e,minivan
45,dodge,caravan 2wd,3.8,1999,6,auto(l4),f,15,22,r,minivan
46,dodge,caravan 2wd,3.8,1999,6,auto(l4),f,15,21,r,minivan
47,dodge,caravan 2wd,3.8,2008,6,auto(l6),f,16,23,r,minivan
48,dodge,caravan 2wd,4.0,2008,6,auto(l6),f,16,23,r,minivan
49,dodge,dakota pickup 4wd,3.7,2008,6,manual(m6),4,15,19,r,pickup
50,dodge,dakota pickup 4wd,3.7,2008,6,auto(l4),4,14,18,r,pickup
51,dodge,dakota pickup 4wd,3.9,1999,6,auto(l4),4,13,17,r,pickup
52,dodge,dakota pickup 4wd,3.9,1999,6,manual(m5),4,14,17,r,pickup
53,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup
54,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup
55,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup
56,dodge,dakota pickup 4wd,5.2,1999,8,manual(m5),4,11,17,r,pickup
57,dodge,dakota pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup
58,dodge,durango 4wd,3.9,1999,6,auto(l4),4,13,17,r,suv
59,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv
60,dodge,durango 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv
61,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv
62,dodge,durango 4wd,5.2,1999,8,auto(l4),4,11,16,r,suv
63,dodge,durango 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv
64,dodge,durango 4wd,5.9,1999,8,auto(l4),4,11,15,r,suv
65,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,12,16,r,pickup
66,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup
67,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup
68,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup
69,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,12,16,r,pickup
70,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,9,12,e,pickup
71,dodge,ram 1500 pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup
72,dodge,ram 1500 pickup 4wd,5.2,1999,8,manual(m5),4,11,16,r,pickup
73,dodge,ram 1500 pickup 4wd,5.7,2008,8,auto(l5),4,13,17,r,pickup
74,dodge,ram 1500 pickup 4wd,5.9,1999,8,auto(l4),4,11,15,r,pickup
75,ford,expedition 2wd,4.6,1999,8,auto(l4),r,11,17,r,suv
76,ford,expedition 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv
77,ford,expedition 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv
78,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv
79,ford,explorer 4wd,4.0,1999,6,manual(m5),4,15,19,r,suv
80,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv
81,ford,explorer 4wd,4.0,2008,6,auto(l5),4,13,19,r,suv
82,ford,explorer 4wd,4.6,2008,8,auto(l6),4,13,19,r,suv
83,ford,explorer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv
84,ford,f150 pickup 4wd,4.2,1999,6,auto(l4),4,14,17,r,pickup
85,ford,f150 pickup 4wd,4.2,1999,6,manual(m5),4,14,17,r,pickup
...,...,...,...,...,...,...,...,...,...,...,...
150,nissan,maxima,3.5,2008,6,auto(av),f,19,25,p,midsize
151,nissan,pathfinder 4wd,3.3,1999,6,auto(l4),4,14,17,r,suv
152,nissan,pathfinder 4wd,3.3,1999,6,manual(m5),4,15,17,r,suv
153,nissan,pathfinder 4wd,4.0,2008,6,auto(l5),4,14,20,p,suv
154,nissan,pathfinder 4wd,5.6,2008,8,auto(s5),4,12,18,p,suv
155,pontiac,grand prix,3.1,1999,6,auto(l4),f,18,26,r,midsize
156,pontiac,grand prix,3.8,1999,6,auto(l4),f,16,26,p,midsize
157,pontiac,grand prix,3.8,1999,6,auto(l4),f,17,27,r,midsize
158,pontiac,grand prix,3.8,2008,6,auto(l4),f,18,28,r,midsize
159,pontiac,grand prix,5.3,2008,8,auto(s4),f,16,25,p,midsize
160,subaru,forester awd,2.5,1999,4,manual(m5),4,18,25,r,suv
161,subaru,forester awd,2.5,1999,4,auto(l4),4,18,24,r,suv
162,subaru,forester awd,2.5,2008,4,manual(m5),4,20,27,r,suv
163,subaru,forester awd,2.5,2008,4,manual(m5),4,19,25,p,suv
164,subaru,forester awd,2.5,2008,4,auto(l4),4,20,26,r,suv
165,subaru,forester awd,2.5,2008,4,auto(l4),4,18,23,p,suv
166,subaru,impreza awd,2.2,1999,4,auto(l4),4,21,26,r,subcompact
167,subaru,impreza awd,2.2,1999,4,manual(m5),4,19,26,r,subcompact
168,subaru,impreza awd,2.5,1999,4,manual(m5),4,19,26,r,subcompact
169,subaru,impreza awd,2.5,1999,4,auto(l4),4,19,26,r,subcompact
170,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,25,p,compact
171,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,27,r,compact
172,subaru,impreza awd,2.5,2008,4,manual(m5),4,19,25,p,compact
173,subaru,impreza awd,2.5,2008,4,manual(m5),4,20,27,r,compact
174,toyota,4runner 4wd,2.7,1999,4,manual(m5),4,15,20,r,suv
175,toyota,4runner 4wd,2.7,1999,4,auto(l4),4,16,20,r,suv
176,toyota,4runner 4wd,3.4,1999,6,auto(l4),4,15,19,r,suv
177,toyota,4runner 4wd,3.4,1999,6,manual(m5),4,15,17,r,suv
178,toyota,4runner 4wd,4.0,2008,6,auto(l5),4,16,20,r,suv
179,toyota,4runner 4wd,4.7,2008,8,auto(l5),4,14,17,r,suv
180,toyota,camry,2.2,1999,4,manual(m5),f,21,29,r,midsize
181,toyota,camry,2.2,1999,4,auto(l4),f,21,27,r,midsize
182,toyota,camry,2.4,2008,4,manual(m5),f,21,31,r,midsize
183,toyota,camry,2.4,2008,4,auto(l5),f,21,31,r,midsize
184,toyota,camry,3.0,1999,6,auto(l4),f,18,26,r,midsize
185,toyota,camry,3.0,1999,6,manual(m5),f,18,26,r,midsize
186,toyota,camry,3.5,2008,6,auto(s6),f,19,28,r,midsize
187,toyota,camry solara,2.2,1999,4,auto(l4),f,21,27,r,compact
188,toyota,camry solara,2.2,1999,4,manual(m5),f,21,29,r,compact
189,toyota,camry solara,2.4,2008,4,manual(m5),f,21,31,r,compact
190,toyota,camry solara,2.4,2008,4,auto(s5),f,22,31,r,compact
191,toyota,camry solara,3.0,1999,6,auto(l4),f,18,26,r,compact
192,toyota,camry solara,3.0,1999,6,manual(m5),f,18,26,r,compact
193,toyota,camry solara,3.3,2008,6,auto(s5),f,18,27,r,compact
194,toyota,corolla,1.8,1999,4,auto(l3),f,24,30,r,compact
195,toyota,corolla,1.8,1999,4,auto(l4),f,24,33,r,compact
196,toyota,corolla,1.8,1999,4,manual(m5),f,26,35,r,compact
197,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact
198,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact
199,toyota,land cruiser wagon 4wd,4.7,1999,8,auto(l4),4,11,15,r,suv
200,toyota,land cruiser wagon 4wd,5.7,2008,8,auto(s6),4,13,18,r,suv
201,toyota,toyota tacoma 4wd,2.7,1999,4,manual(m5),4,15,20,r,pickup
202,toyota,toyota tacoma 4wd,2.7,1999,4,auto(l4),4,16,20,r,pickup
203,toyota,toyota tacoma 4wd,2.7,2008,4,manual(m5),4,17,22,r,pickup
204,toyota,toyota tacoma 4wd,3.4,1999,6,manual(m5),4,15,17,r,pickup
205,toyota,toyota tacoma 4wd,3.4,1999,6,auto(l4),4,15,19,r,pickup
206,toyota,toyota tacoma 4wd,4.0,2008,6,manual(m6),4,15,18,r,pickup
207,toyota,toyota tacoma 4wd,4.0,2008,6,auto(l5),4,16,20,r,pickup
208,volkswagen,gti,2.0,1999,4,manual(m5),f,21,29,r,compact
209,volkswagen,gti,2.0,1999,4,auto(l4),f,19,26,r,compact
210,volkswagen,gti,2.0,2008,4,manual(m6),f,21,29,p,compact
211,volkswagen,gti,2.0,2008,4,auto(s6),f,22,29,p,compact
212,volkswagen,gti,2.8,1999,6,manual(m5),f,17,24,r,compact
213,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact
214,volkswagen,jetta,2.0,1999,4,manual(m5),f,21,29,r,compact
215,volkswagen,jetta,2.0,1999,4,auto(l4),f,19,26,r,compact
216,volkswagen,jetta,2.0,2008,4,auto(s6),f,22,29,p,compact
217,volkswagen,jetta,2.0,2008,4,manual(m6),f,21,29,p,compact
218,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact
219,volkswagen,jetta,2.5,2008,5,manual(m5),f,21,29,r,compact
220,volkswagen,jetta,2.8,1999,6,auto(l4),f,16,23,r,compact
221,volkswagen,jetta,2.8,1999,6,manual(m5),f,17,24,r,compact
222,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact
223,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact
224,volkswagen,new beetle,2.0,1999,4,manual(m5),f,21,29,r,subcompact
225,volkswagen,new beetle,2.0,1999,4,auto(l4),f,19,26,r,subcompact
226,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact
227,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact
228,volkswagen,passat,1.8,1999,4,manual(m5),f,21,29,p,midsize
229,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

# Exercises

Create a directory named spark within your ds-methodologies repository. This is where you will do the exercises for this module.

Create a jupyter notebook or python script named spark101 for this exercise.

1. Create a spark data frame that contains your favorite programming languages.

    - The name of the column should be language
    - View the schema of the dataframe
    - Output the shape of the dataframe
    - Show the first 5 records in the dataframe


2. Load the mpg dataset as a spark dataframe.

    - Create 1 column of output that contains a message like the one below:
             
            The 1999 audi a4 has a 4 cylinder engine.
            For each vehicle.
            
    - Transform the trans column so that it only contains either manual or auto. 
  

3. Load the tips dataset as a spark dataframe.

    - What percentage of observations are smokers?
    - Create a column that contains the tip percentage
    - Calculate the average tip percentage for each combination of sex and smoker.


4. Use the seattle weather dataset referenced in the lesson to answer the questions below.

   - Convert the temperatures to farenheight.
   - Which month has the most rain, on average?
   - Which year was the windiest?
   - What is the most frequent type of weather in January?
   - What is the average high and low tempurature on sunny days in July in 2013 and 2014?
   - What percentage of days were rainy in q3 of 2015?
   - For each year, find what percentage of days it rained (had non-zero precipitation).

In [16]:
import pyspark
import pandas as pd

In [17]:
spark = pyspark.sql.SparkSession.builder.getOrCreate()

1. Create a spark data frame that contains your favorite programming languages.

    - The name of the column should be language
    - View the schema of the dataframe
    - Output the shape of the dataframe
    - Show the first 5 records in the dataframe

In [37]:
data = ['python', 'java', 'jupyter', 'C++', 'C#', 'clojure']

In [46]:
pandas_dataframe = pd.DataFrame(pd.Series(data), columns=['language'])
pandas_dataframe

  language
0   python
1     java
2  jupyter
3      C++
4       C#
5  clojure

In [51]:
df = spark.createDataFrame(pandas_dataframe)
df.show(5)

+--------+
|language|
+--------+
|  python|
|    java|
| jupyter|
|     C++|
|      C#|
+--------+
only showing top 5 rows

2. Load the mpg dataset as a spark dataframe.

    - Create 1 column of output that contains a message like the one below:
             
            The 1999 audi a4 has a 4 cylinder engine.
            For each vehicle.
            
    - Transform the trans column so that it only contains either manual or auto.

In [72]:
from pydataset import data

In [73]:
mpg = data('mpg')

In [74]:
mpg.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [75]:
mpg = spark.createDataFrame(mpg)

In [76]:
mpg.show(5)

+------------+-----+-----+----+---+----------+---+---+---+---+-------+
|manufacturer|model|displ|year|cyl|     trans|drv|cty|hwy| fl|  class|
+------------+-----+-----+----+---+----------+---+---+---+---+-------+
|        audi|   a4|  1.8|1999|  4|  auto(l5)|  f| 18| 29|  p|compact|
|        audi|   a4|  1.8|1999|  4|manual(m5)|  f| 21| 29|  p|compact|
|        audi|   a4|  2.0|2008|  4|manual(m6)|  f| 20| 31|  p|compact|
|        audi|   a4|  2.0|2008|  4|  auto(av)|  f| 21| 30|  p|compact|
|        audi|   a4|  2.8|1999|  6|  auto(l5)|  f| 16| 26|  p|compact|
+------------+-----+-----+----+---+----------+---+---+---+---+-------+
only showing top 5 rows

In [77]:
mpg.printSchema()

root
 |-- manufacturer: string (nullable = true)
 |-- model: string (nullable = true)
 |-- displ: double (nullable = true)
 |-- year: long (nullable = true)
 |-- cyl: long (nullable = true)
 |-- trans: string (nullable = true)
 |-- drv: string (nullable = true)
 |-- cty: long (nullable = true)
 |-- hwy: long (nullable = true)
 |-- fl: string (nullable = true)
 |-- class: string (nullable = true)

In [78]:
mpg.count(), len(mpg.columns)

(234, 11)

In [81]:
mpg.select(concat(
    lit('The')
    col('year')
    lit(' ')
    col('manufacturer')
    lit(' ')
    col('model')
    lit(' has a ')
    col('cyl')
    lit(' cylinder engine'),
).alias('vehicle_cylinder_description')).show(truncate=False)

SyntaxError: invalid syntax (<ipython-input-81-9597f77f2d0b>, line 3)

3. Load the tips dataset as a spark dataframe.

    - What percentage of observations are smokers?
    - Create a column that contains the tip percentage
    - Calculate the average tip percentage for each combination of sex and smoker.

In [82]:
tips = spark.createDataFrame(pydataset.data('tips'))
tips.show(5)

+----------+----+------+------+---+------+----+
|total_bill| tip|   sex|smoker|day|  time|size|
+----------+----+------+------+---+------+----+
|     16.99|1.01|Female|    No|Sun|Dinner|   2|
|     10.34|1.66|  Male|    No|Sun|Dinner|   3|
|     21.01| 3.5|  Male|    No|Sun|Dinner|   3|
|     23.68|3.31|  Male|    No|Sun|Dinner|   2|
|     24.59|3.61|Female|    No|Sun|Dinner|   4|
+----------+----+------+------+---+------+----+
only showing top 5 rows

4. Use the seattle weather dataset referenced in the lesson to answer the questions below.

   - Convert the temperatures to farenheight.
   - Which month has the most rain, on average?
   - Which year was the windiest?
   - What is the most frequent type of weather in January?
   - What is the average high and low tempurature on sunny days in July in 2013 and 2014?
   - What percentage of days were rainy in q3 of 2015?
   - For each year, find what percentage of days it rained (had non-zero precipitation).

In [83]:
from vega_datasets import data

weather = data.seattle_weather().assign(date=lambda df: df.date.astype(str))
weather = spark.createDataFrame(weather)
weather.show(6)

+----------+-------------+--------+--------+----+-------+
|      date|precipitation|temp_max|temp_min|wind|weather|
+----------+-------------+--------+--------+----+-------+
|2012-01-01|          0.0|    12.8|     5.0| 4.7|drizzle|
|2012-01-02|         10.9|    10.6|     2.8| 4.5|   rain|
|2012-01-03|          0.8|    11.7|     7.2| 2.3|   rain|
|2012-01-04|         20.3|    12.2|     5.6| 4.7|   rain|
|2012-01-05|          1.3|     8.9|     2.8| 6.1|   rain|
|2012-01-06|          2.5|     4.4|     2.2| 2.2|   rain|
+----------+-------------+--------+--------+----+-------+
only showing top 6 rows